{% set version = "0.9.1" %}
{% set sha256 = "eb37ef775280a54be5d7f949849fc5f016ed6584410c7888d4f6d015a8ce8675" %}
{% set build_number = 1 %}

package:
  name: "pdgstaging"
  version: {{ version }}

source:
  url: https://github.com/PermafrostDiscoveryGateway/viz-staging/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build_number }}

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.2,<2.0
    - pandas >=1.4,<2.0
    - shapely >=2,<3.0
    - geopandas >=0.12.2,<1.0
    - morecantile >=3.1,<4.0
    - rtree >=0.9,<1.0
    - filelock >=3.6,<4.0
    - coloraide >=0.10,<1.0
    - colormaps ==0.4.0

    # HACK: block transitive dependency incompatibilities
    # See pending fix in upstream repo: https://github.com/PermafrostDiscoveryGateway/viz-staging/pull/51
    - pydantic <2.0
    - fiona <1.9

test:
  imports:
    - pdgstaging
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PermafrostDiscoveryGateway/viz-staging
  license: Apache-2.0
  license_file: LICENSE
  summary: Polar Discovery Gateway visualization staging software

extra:
  recipe-maintainers:
    - mfisher87
    - rushirajnenuji
